on:
  # develop에 push 되었을 때
  push:
    branches: [ develop ]

jobs:
  sync:
    runs-on: ubuntu-latest
    name: sync-test
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2.3.3
      with:
        # 레포지토리에 접속
        repository: givinkwon/boltnnut-platform-front
        lfs: true
        ref: develop
        token: ${{ secrets.SYNC || github.token }} 
    # git에 log 남기기
    - run: git log
      shell: bash
    # 동기화하기
    - uses: givinkwon/sync-repo-to-repo@v1.3
      with:
        source-repo: https://github.com/givinkwon/boltnnut-platform-front-test
    # 완료되었음 로그
    - run: echo sync completed!
      shell: bash
