on:
  schedule:
  - cron: '0 18 * * *'
  workflow_dispatch: 
    inputs: 
        source-repo:
          description: source-repo
        target-repo:
          description: target-repo

jobs:
  sync:
    runs-on: ubuntu-latest
    name: sync-test
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: givinkwon/boltnnut-platform-front-test
        token: ${{ secrets.SYNC || github.token }} 
        ref: master
    - run: git log
      shell: bash
    - uses: givinkwon/sync-repo-to-repo@v1.1
      with:
        source-repo: https://github.com/givinkwon/boltnnut-platform-front
        target-repo: givinkwon/boltnnut-platform-front-test
    - run: echo sync completed!
      shell: bash
